### ISSUE TITLE
Feature Request: support loading csv from a file

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm-Exchange/stackstorm-csv#2]
I would like to retrieve configuration values from a CSV file. The parse action, however, requires a string. I thought about using another pack to load the file and pass it as a string to this module, but there aren't any "core.read_file" or "linux.read_file" actions.

**Comment by nzlosh** [comment]
I don't disagree with having such functionality, as a workaround, have you considered using `core.local` to read the file using `cat /path/to/file` to get the contents?

**Comment by Kami** [comment]
Yeah using a workflow where first task / action does something like `cat /path/to/file` and the second one uses `csv.parse` should work and is a common pattern across the board.

In short, the idea behind most actions is to provide small atomic functionality so this action only operates with strings. If you want more complex functionality or similar you can achieve that bu composing multiple actions together in a workflow.

Another option would also be to add `csv.parse_file` action to this pack.

**Comment by Kami** [comment]
#3 should do it.

For consistency, I will go ahead and add the same `parse_file` action to the XML pack.

**Comment by Kami** [comment]
Corresponding xml pack change - https://github.com/StackStorm-Exchange/stackstorm-xml/pull/2.
